name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y python3 python3-pip openjdk-17-jdk unzip git

    - name: Install Buildozer
      run: pip install buildozer cython

    - name: Init Buildozer
      run: buildozer init

    - name: Configure Buildozer
      run: |
        sed -i 's/^requirements = .*/requirements = python3,kivy,pandas,openpyxl/' buildozer.spec
        echo "source.include_exts = py,xlsx" >> buildozer.spec

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
